### ISSUE TITLE
Add Youtube Data Connector

### ISSUE THREAD

**Issue by nickscamara** [mendableai/data-connectors#1]
Add a Youtube data connector that grabs the transcript of the video URLs passed in.

It should also have a mode option where one mode is `video-urls` and the other is `channel`.

If channel mode is selected, it will get the transcripts for every video in the channel url. If the video urls is selected, it will get the transcript for only the videos URLs passed in.

Returns in the Document format with content being the transcript and metadata.sourceUrl being the video url.

Other requirements:
- Make sure to add proper tests inside the __tests__ folder
- If an added env is required, please update the env.example

**Comment by nickscamara** [comment]
/bounty $30

If merged and is of high quality within 24 hours of the assignment, a $10 tip will be added :)

**Comment by ibishal** [comment]
/attempt #1
can i get assigned?

**Comment by nickscamara** [comment]
@ibishal assigning you. 

@guptadeepak8 if @ibishal doesn't PR in 48 hours, you can start your attempt. Thank you!

**Comment by akhilphenom** [comment]
would you give channelUrls[]? or simply channel?

**Comment by ibishal** [comment]
@akhilphenom i was assigned and working on it 🙄

**Comment by nickscamara** [comment]
@akhilphenom please don't do this anymore. This was already assigned to @ibishal. It puts us in an awkward situation.

**Comment by nickscamara** [comment]
Closing this for now.
