### ISSUE TITLE
Add Confluence Connector

### ISSUE THREAD

**Issue by nickscamara** [mendableai/data-connectors#2]
Add a confluence data connector that grabs all the wiki pages `/wiki/api/v2/pages` in getDocuments. Should implement authorizeNango. Make sure to have proper pagination as well.

Other requirements:
- Make sure to add proper tests inside the __tests__ folder
- If an added env is required, please update the env.example

**Comment by nickscamara** [comment]
/bounty $40

If merged and is of high quality within 24 hours of the assignment, a $10 tip will be added :)

**Comment by nickscamara** [comment]
@b4s36t4 assigned you

**Comment by b4s36t4** [comment]
Hi, @nickscamara. I have some questions. can I ask here?

**Comment by b4s36t4** [comment]
Are we going to `OAuth` method for authorising confluence or `Basic` auth?
If it's `OAuth` we must be providing `redirect_uri` which the user will put in their OAuth Settings and once authentication is done from the user's end (who is trying auth) atlassian will redirect that user to the website they've entered which we cannot predict and read the code.

more on this here - https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/

**Comment by nickscamara** [comment]
@b4s36t4 feel free to only implement the authorizeNango section. With that one, you don't need to deal with this. I will update the description!

**Comment by nickscamara** [comment]
@b4s36t4 how's everything going?

**Comment by nickscamara** [comment]
@rishi-raj-jain go for it.

**Comment by rishi-raj-jain** [comment]
@mogery please crush this as well haha?

**Comment by mogery** [comment]
Sure 😅  cc @nickscamara

**Comment by nickscamara** [comment]
@mogery all yours!
