### ISSUE TITLE
Notion integration rate limiting

### ISSUE THREAD

**Issue by nickscamara** [mendableai/data-connectors#20]
It seems like Notion rate limits when ingesting tons of documents. The idea here would be to implement a strategy to prevent us from getting rate limited and also retry with expo backoff so it doesn't fail

Here are the docs for it. https://developers.notion.com/reference/request-limits

**Comment by nickscamara** [comment]
@mogery wanna tackle this?

**Comment by nickscamara** [comment]
\bounty $20

**Comment by feliciien** [comment]
can i get   assigned to this issue

**Comment by shashank40** [comment]
/attempt [#20](https://github.com/mendableai/data-connectors/issues/20)
Hey @nickscamara , i wanted to attempt this issue and so i added a PR too for you to have a look.
[#21 ](https://github.com/mendableai/data-connectors/pull/21)

**Comment by mogery** [comment]
> @mogery wanna tackle this?

sorry, i'm super busy this week, couldn't get on it
