### ISSUE TITLE
Add Microsoft OneDrive as a data connector

### ISSUE THREAD

**Issue by ericciarla** [mendableai/data-connectors#28]
Add a Microsoft OneDrive connector that grabs the same all files and folders as the Google drive connector (https://github.com/mendableai/data-connectors/tree/main/src/providers/GoogleDrive)

Should authorize with nango etc, following the github/google drive implementations.

Other requirements:

Make sure to add proper tests inside the tests folder
If an added env is required, please update the env.example
https://docs.nango.dev/integrations/all/one-drive

DO NOT START WORKING ON THIS BEFORE GETTING ASSIGNED, OTHERWISE WE CAN'T AWARD THE BOUNTY

**Comment by mogery** [comment]
> @mogery are you interested in this?

yes! i can get it done in 24h

**Comment by ericciarla** [comment]
Awesome!!

**Comment by mogery** [comment]
Working on this right now. Will be up in ~1 hour. Sorry about the delay.

**Comment by ericciarla** [comment]
Nice job @mogery! Sorry about the delay, thank you for contributing as always 🚀
