### ISSUE TITLE
Add Public GitHub Connector

### ISSUE THREAD

**Issue by nickscamara** [mendableai/data-connectors#3]
This data connector should get all the files inside a github repository. It must contain the following options: branch, doc only mode (only returns .md, .txt, .rst, .mdx) and folder path (if docs/ is specified for example, it must only return the documents inside the folder)

Recommend using Octokit*

Other requirements:
- Make sure to add proper tests inside the __tests__ folder
- If an added env is required, please update the env.example

**Comment by nickscamara** [comment]
/bounty $30

If merged and is of high quality within 24 hours of the assignment, a $10 tip will be added :)

**Comment by rishi-raj-jain** [comment]
/attempt #3

Can I get assigned?

**Comment by nickscamara** [comment]
@rishi-raj-jain all yours!

**Comment by mogery** [comment]
I'd like to attempt this as well.

**Comment by nickscamara** [comment]
@mogery feel free to attempt it!
