### ISSUE TITLE
Add Jira Data Connector

### ISSUE THREAD

**Issue by nickscamara** [mendableai/data-connectors#5]
Add a Jira data connector that grabs all the JIRA issues. This needs to be authorized with Nango just like the Google Drive implementation.

This should help implement the getDocuments function: https://github.com/NangoHQ/nango/blob/master/integration-templates/jira/jira-issues.ts

Other requirements:
- Make sure to add proper tests inside the tests folder
- If an added env is required, please update the env.example

https://docs.nango.dev/integrations/all/jira

**DO NOT START WORKING ON THIS BEFORE GETTING ASSIGNED, OTHERWISE WE CAN'T AWARD THE BOUNTY**

**Comment by nickscamara** [comment]
@ibishal wanna work on this one? if so I will assign and prioritize a bounty for you.

**Comment by ibishal** [comment]
ok @nickscamara

**Comment by nickscamara** [comment]
@ibishal all yours.

**Comment by ibishal** [comment]
@nickscamara should i make classes for the api or should i use `jira-js` wrapper

**Comment by nickscamara** [comment]
@ibishal jira-js should be fine.

**Comment by chnrv99** [comment]
Can you assign me? I would like to work on it.

**Comment by nickscamara** [comment]
Go for it @chnrv99

**Comment by chnrv99** [comment]
Hey, really sorry but I can't work on this right now. Have some life situation rn(please try to understand). Really sorry, this was unexpected to me.

**Comment by nickscamara** [comment]
@chnrv99 no worries at all. Hope all is well.

**Comment by mogery** [comment]
I can get on this actually. Turn-in likely by Jan 31 8PM CET.

**Comment by nickscamara** [comment]
Go for it! @mogery
