### ISSUE TITLE
Add Notion Data Connector

### ISSUE THREAD

**Issue by nickscamara** [mendableai/data-connectors#8]
Add a Notion data connector that grabs all the content from all the pages in the authorized workspaces. **That means it needs to attempt to get all the contents inside all nested databases in notion etc.**  Should authorize with nango etc, following the github/google drive implementations.

This should help implement the getDocuments function: https://github.com/NangoHQ/nango/blob/master/integration-templates/notion/notion-pages.ts

Other requirements:

- Make sure to add proper tests inside the tests folder
- If an added env is required, please update the env.example

https://docs.nango.dev/integrations/all/notion

DO NOT START WORKING ON THIS BEFORE GETTING ASSIGNED, OTHERWISE WE CAN'T AWARD THE BOUNTY

**Comment by nickscamara** [comment]
@mogery wanna work on this? If so, I create a bounty and assign you to it.

**Comment by mogery** [comment]
Hell yeah!

**Comment by mogery** [comment]
@nickscamara What format should the pages be returned in? Is JSON fine, should I convert everything to markdown for easy parsing, or perhaps just dump out all the text?

**Comment by nickscamara** [comment]
You can just dump all the raw text into content .

**Comment by nickscamara** [comment]
@mogery  Actually, if converting to markdown is easy and won't take too much time, that would be great

**Comment by mogery** [comment]
Due to API limitations, only Notion pages that have been connected with the integration will be available to the data connector. I've recorded a GIF on how to do this: my integration in this example is called "mendable test".

![ScreenRecording2024-01-30at21 20 00-ezgif com-video-to-gif-converter](https://github.com/mendableai/data-connectors/assets/66118807/1830f5a2-2c12-4c09-ac31-7249e2481e6c)

**Comment by nickscamara** [comment]
@mogery sounds good. Would the child page of that page be accessible if you add a connection to the parent page? Also, does the same apply to databases? Thank you :)

**Comment by mogery** [comment]
> @mogery sounds good. Would the child page of that page be accessible if you add a connection to the parent page? Also, does the same apply to databases? Thank you :)

Yup, access travels down the parent-child tree. Checking for databases now.

**Comment by mogery** [comment]
Yeah, access also travels to databases, and nested pages are automatically included in the list query :) Opening PR...

![Screenshot 2024-01-30 at 21 31 55](https://github.com/mendableai/data-connectors/assets/66118807/8aaa043f-a6cc-46ce-8b64-a2531d5691b6)

**Comment by nickscamara** [comment]
Awesome!!! @mogery
